### PR TITLE
Changes by H.T.

### PR DESCRIPTION
**Pull request by IntruderHT**
Hello from Germany
Here´s my Change-Log

I have fixed some lines to make translation more comfortable. Also I added a few more images to the bottom of the created Ticket. So there is a option to put some Sponsors on the Bottom-Line manually. 
Greetings 
Holger Theuer
H.T.

Change Log:

inc\core\post-type.class.php

To grant a proper title for other languages. To make changes take effect to existing Events, once all events have to be updated.

Line
897
950
980	from:	'post_title' => sprintf(__('%s on %s @ %s','qsot'), $post->post_title, date( $date_format, $d), date('g:ia', $d)), // create a pretty proper title
	to:	'post_title' => sprintf(__('%s on %s @ %s','opentickets-community-edition'), $post->post_title, date( $date_format, $d), date(__('g:ia','opentickets-community-edition'), $d)), // create a pretty proper title

inc\core\post-type.class.php

For translation of the @ of Begin Start/Time in "Event Run Date Range" Widget 

Line
1139 	from:	<td width="1%">@</td> 
	        to: 	<td width="1%"><?php _e('@','opentickets-community-edition') ?></td>
	
	

templates\checkin\already-occupied.php

Line
9	from:	$msg = 'Ticket has PREVIOUSLY checked in!';
	to:	$msg = __('Ticket has PREVIOUSLY checked in!','opentickets-community-edition');

email-order-items.php

For translation of the # in order email

Line
33	from:	echo ' (#' . $_product->get_sku() . ')';
	to:	echo ' (' . __('#', 'opentickets-community-edition' ) . $_product->get_sku() . ')';

templates\tickets\basic-ticket.php

Added 5 more images that can be replaced manually with Sponsor-Images

Line
84-106	<table>
	<tbody>
	<tr><td>
	<a href="<?php echo esc_attr( QSOT::product_url() ) ?>" title="<?php _e('Who is OpenTickets?','opentickets-community-edition') ?>">
	" class="ot-tiny-logo" />
	</a></td><td>
	<a href="<?php echo esc_attr( QSOT::product_url() ) ?>" title="<?php _e('Who is OpenTickets?','opentickets-community-edition') ?>">
	" class="ot-tiny-logo" />
	</a></td><td>
	<a href="<?php echo esc_attr( QSOT::product_url() ) ?>" title="<?php _e('Who is OpenTickets?','opentickets-community-edition') ?>">
	" class="ot-tiny-logo" />
	</a></td><td>
	<a href="<?php echo esc_attr( QSOT::product_url() ) ?>" title="<?php _e('Who is OpenTickets?','opentickets-community-edition') ?>">
	" class="ot-tiny-logo" />
	</a></td><td>
	<a href="<?php echo esc_attr( QSOT::product_url() ) ?>" title="<?php _e('Who is OpenTickets?','opentickets-community-edition') ?>">
	" class="ot-tiny-logo" />
	</a></td><td>
	<a href="<?php echo esc_attr( QSOT::product_url() ) ?>" title="<?php _e('Who is OpenTickets?','opentickets-community-edition') ?>">
	" class="ot-tiny-logo" />
	</a></td></tr>
	</tbody>
	</table>

templates\tickets\basic-style.css

to align the Sponsor images to the bottom of the ticket

Line
18	from:	.page-wrap .ot-tiny-logo { position:absolute; margin:1px 0 0 -8px; }
	to:	.page-wrap .ot-tiny-logo { position:absolute; bottom: 0; margin:1px 0 0 -8px; }
	

All Language-Files updated

### CODE REVIEW

**Comment by loushou** [comment]
Hey @IntruderHT,

I like most of this. I do have a few questions and suggestions though, before I merge it in.

1. Suggestion: we should probably __() the word 'of' on line 74 of templates/tickets/basic-ticket.php, since we are __() all the other strings in the area.

2. Question: in templates/tickets/basic-ticket.php, on line 69, I notice you added a space between '#' and the order number. is that intentional? the reason I ask is because, everywhere else in WooCommerce that the order number appears with a # before it, the number is adjacent to the #, and there is no space. should it have no space, for consitency?

3. Question: in templates/tickets/basic-ticket.php, after line 84, why is there 5 copies of the open tickets image? is that intentional?

4. Question: in templates/tickets/basic-ticket.php, on line 88, what is assets/imgs/loers-ticket.png? I don't see that as a new file. If that is a custom branding image, that should be removed for the base plugin.

Thanks,
Loushou

**Comment by IntruderHT** [comment]
Hey loushou,

thanks for your reply. 

To 
1. Yes you´re right. The word 'of' have to be translated too.

2. Yes i set the space intentional. But it is not elementary. If Woocommerce don't set a space between the '#' and the order number, delete the space please, to hold the code consistently. In Germany you have to set a space between the abbreviation and the number. 
Like this: Art.-Nr.: 123456
I can set the spacer in the translation.

3. The 5 copies are a suggestion to you. My intention was, that the user have an option to put some Sponsor images at the bottom-line of the ticket. I must admit that it is not very comfortable yet. This makes more sense, if the hard coded path of the images can be set in the admin menu. If you don't like it, kill it  ;)

4. That's my fault. It is a custom branding image. Copy/paste error. Sorry.

Greetings
Holger

**Comment by loushou** [comment]
Hey @IntruderHT,

Thanks for the response. I will get this merged in, and a new release made. I will close this pull request after it has been completed.

Loushou

**Comment by loushou** [comment]
Hey @IntruderHT,

I got this integrated now, along with lots of updates to improve the ticket experience. As you suggested, I also added the ability to chose additional branding images on your tickets, configurable in the admin. Thanks for the great updates and suggestions.

Loushou

**Pull request merged**
